---
- etckeeper: action=begin


- name: Create domain configuration file
  copy:
    content: "{{ dehydrated_domains | mandatory }}"
    dest: "{{ dehydrated_configdir }}/domains.txt"
    owner: "{{ dehydrated_username }}"
    group: "{{ dehydrated_usergroup }}"


- name: Check for old configuration file
  stat: path={{ dehydrated_configdir }}/config.sh
  always_run: yes
  register: dehydrated_old_config_dir
  tags:
  - skip_ansible_lint # for now, cf. https://github.com/geerlingguy/ansible-role-mysql/issues/179#issuecomment-259762499
- name: Move old configuration file to new place
  command: mv {{ dehydrated_configdir }}/config.sh {{ dehydrated_configdir }}/config
  when: dehydrated_old_config_dir.stat.exists


- name: Copy config example to configuration directory
  copy:
    src: "{{ dehydrated_userhome }}/dehydrated/docs/examples/config"
    dest: "{{ dehydrated_configdir }}/config"
    remote_src: true
    force: false
    owner: "{{ dehydrated_username }}"
    group: "{{ dehydrated_usergroup }}"

- name: Set BASEDIR value to dehydrated_configdir value
  lineinfile:
    dest: "{{ dehydrated_configdir }}/config"
    regexp: "^#?BASEDIR"
    line: "BASEDIR=\"{{ dehydrated_configdir }}\""

- name: Set WELLKNOWN value to dehydrated_challengesdir value
  lineinfile:
    dest: "{{ dehydrated_configdir }}/config"
    regexp: "^#?WELLKNOWN"
    line: "WELLKNOWN=\"{{ dehydrated_challengesdir }}\""

- name: Set PRIVATE_KEY_RENEW value to dehydrated_privatekeyrenew value
  lineinfile:
    dest: "{{ dehydrated_configdir }}/config"
    regexp: "^#?PRIVATE_KEY_RENEW"
    line: "PRIVATE_KEY_RENEW=\"{{ dehydrated_privatekeyrenew }}\""

- name: Set CONTACT_EMAIL value to dehydrated_contactemail value
  lineinfile:
    dest: "{{ dehydrated_configdir }}/config"
    regexp: "^#?CONTACT_EMAIL"
    line: "CONTACT_EMAIL=\"{{ dehydrated_contactemail | mandatory }}\""

- name: Set OCSP_MUST_STAPLE value to dehydrated_ocsp_must_staple value
  lineinfile:
    dest: "{{ dehydrated_configdir }}/config"
    regexp: "^#?OCSP_MUST_STAPLE"
    line: "OCSP_MUST_STAPLE=\"{{ dehydrated_ocsp_must_staple }}\""

- name: Set LICENSE value to dehydrated_letsencrypt_agreed_terms value
  lineinfile:
    dest: "{{ dehydrated_configdir }}/config"
    regexp: "^#?LICENSE"
    line: "LICENSE=\"{{ dehydrated_letsencrypt_agreed_terms }}\""


- name: Set path to certificate authority
  lineinfile:
    dest: "{{ dehydrated_configdir }}/config"
    regexp: "^#?CA"
    line: "CA=\"{{ dehydrated_acme_api }}\""

- etckeeper: "action=commit msg='ansible: {{ vars['role_name']}}.configure' rev={{ revision }}"
