---


- name: Create domain configuration file
  copy:
    content: "{{ dehydrated_domains | mandatory }}"
    dest: "{{ dehydrated_configdir }}/domains.txt"
    owner: "{{ dehydrated_username }}"
    group: "{{ dehydrated_usergroup }}"


- name: Check for old configuration file
  stat: path={{ dehydrated_configdir }}/config.sh
  always_run: yes
  register: dehydrated_old_config_dir
  tags:
  - skip_ansible_lint # for now, cf. https://github.com/geerlingguy/ansible-role-mysql/issues/179#issuecomment-259762499
- name: Move old configuration file to new place
  command: mv {{ dehydrated_configdir }}/config.sh {{ dehydrated_configdir }}/config
  when: dehydrated_old_config_dir.stat.exists


- name: Copy config example to configuration directory
  copy:
    src: "{{ dehydrated_userhome }}/dehydrated/docs/examples/config"
    dest: "{{ dehydrated_configdir }}/config"
    remote_src: true
    force: false
    owner: "{{ dehydrated_username }}"
    group: "{{ dehydrated_usergroup }}"

- name: Configure Dehydrated
  lineinfile:
    dest: "{{ dehydrated_configdir }}/config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ dehydrated_config_values }}"
