---
- etckeeper: action=begin


- name: Create group for user {{ lcsh_username }}
  group:
    name: "{{ lcsh_usergroup }}"


- name: Create user for {{ lcsh_username }}
  user:
    name: "{{ lcsh_username }}"
    home: "{{ lcsh_userhome }}"
    group: "{{ lcsh_usergroup }}"


- name: Set paranoid umask for user
  lineinfile:
    dest: "{{ lcsh_userhome }}/.profile"
    regexp: "^#?umask"
    line: "umask 0077 # paranoid umask, we're creating private keys "


- name: Create configuration directory {{ lcsh_configdir }}
  file:
    path: "{{ lcsh_configdir }}"
    state: directory
    owner: "{{ lcsh_username }}"
    group: "{{ lcsh_usergroup }}"
    mode: 0700


- name: Create acme-challenges directory {{ lcsh_challengesdir }}
  file:
    path: "{{ lcsh_challengesdir }}"
    state: directory
    owner: "{{ lcsh_username }}"
    group: "{{ lcsh_usergroup }}"
    mode: 0700


- etckeeper: "action=commit msg='ansible: {{ vars['role_name']}}.user_and_dirs' rev={{ revision }}"
